version: "3.8"

services:
  # Приложение для фронтенда (CRA)
  mnogosushi_cra-app:
    build:
      context: ../client
      dockerfile: dockerfile
    restart: always
    ports:
      - "7000:5000" # Маппинг порта хоста 7000 на порт контейнера 5000
    networks:
      - client_mnogosushi_network

  # Приложение для админки (Vite)
  mnogosushi_vite-app:
    build:
      context: ../admin
      dockerfile: dockerfile
    restart: always
    ports:
      - "7001:5001" # Маппинг порта хоста 7001 на порт контейнера 5001
    networks:
      - client_mnogosushi_network

  # Nginx для проксирования запросов
  mnogosushi_client_nginx:
    image: nginx:latest
    ports:
      - "80:80" # HTTP (будет доступен на localhost:80)
      - "443:443" # HTTPS (будет доступен на localhost:443)
    volumes:
      - ../nginx/nginx.server.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt # SSL-сертификаты
      - /var/www/certbot:/var/www/certbot # Для Certbot, если используется
    depends_on:
      - mnogosushi_cra-app
      - mnogosushi_vite-app
    networks:
      - client_mnogosushi_network
    restart: always

networks:
  client_mnogosushi_network:
    driver: bridge
