services:
  cra-app:
    build:
      context: ../client
      dockerfile: dockerfile
    restart: always
    ports:
      - '5000:5000'
    networks:
      - client_mnogosushi_network

  vite-app:
    build:
      context: ../admin
      dockerfile: dockerfile
    restart: always
    ports:
      - '5001:5001'
    networks:
      - client_mnogosushi_network

  nginx:
    image: nginx:latest
    ports:
      - '7000:80'
      - '7001:81'
    volumes:
      - ../nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - cra-app
      - vite-app
    networks:
      - client_mnogosushi_network
    restart: always

networks:
  client_mnogosushi_network:
    driver: bridge
