version: "3.8"

services:
  mnogosushi_cra-app:
    build:
      context: ../client
      dockerfile: dockerfile
    restart: always
    ports:
      - "5000:5000"
    networks:
      - client_mnogosushi_network

  mnogosushi_vite-app:
    build:
      context: ../admin
      dockerfile: dockerfile
    restart: always
    ports:
      - "5001:5001"
    networks:
      - client_mnogosushi_network

  mnogosushi_client_nginx:
    image: nginx:latest
    ports:
      - "7000:80"
      - "7001:443"
    volumes:
      - ../nginx/nginx.server.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - mnogosushi_cra-app
      - mnogosushi_vite-app
    networks:
      - client_mnogosushi_network
    restart: always

networks:
  client_mnogosushi_network:
    driver: bridge
