name: React CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [admin, client]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Укажите вашу версию Node.js

      - name: Install dependencies
        run: |
          cd ${{ matrix.app }}
          npm install --force

      - name: Run tests
        run: |
          cd ${{ matrix.app }}
          npm test -- --watchAll=false

      - name: Build application
        run: |
          cd ${{ matrix.app }}
          npm run build

      - name: Deploy
        run: |
          echo "Deploying ${{ matrix.app }} application..."
          echo "suka"
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@90.156.230.50 << EOF
          cd mbogosushi_prod_v.0.0.5
          docker-compose -f docker/docker-compose.server.yml up -d --build
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Используйте GitHub token для доступа к репозиторию
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}