name: React CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [admin, client]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Specify your Node.js version

      - name: Install dependencies
        run: |
          cd ${{ matrix.app }}
          npm install --force

      - name: Run tests
        run: |
          cd ${{ matrix.app }}
          npm test -- --watchAll=false

      - name: Build application
        run: |
          cd ${{ matrix.app }}
          npm run build

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: 90.156.230.50
          username: binniev
          password: ${{ secrets.SSH_PASSWORD }}  # Store your SSH password in GitHub Secrets
          source: "./${{ matrix.app }}/dist/*"  # Adjust the path to your build artifacts
          target: "/path/on/server"  # Specify the target path on your server
