name: React CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [admin, client]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Укажите вашу версию Node.js

      - name: Install dependencies
        run: |
          cd ${{ matrix.app }}
          npm install

      - name: Run tests
        run: |
          cd ${{ matrix.app }}
          npm test -- --watchAll=false

      - name: Build application
        run: |
          cd ${{ matrix.app }}
          npm run build

      - name: Deploy
        run: |
          cd ${{ matrix.app }}
          # Добавьте команду для развертывания вашего приложения
          # Например, если используете GitHub Pages, используйте npx gh-pages -d build
          echo "Deploying ${matrix.app} application..."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Используйте GitHub token для доступа к репозиторию
